name: 'auth_service'

services:
  
  domic.auth.api:
    networks:
      - domic
    image: auth_service:1.0.0
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 150M
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "1040-1060:443"
    volumes:
      - log:/app/CoreLogs
      - ~\.aspnet\https\:/https/
    environment:
      - Elastic-Host=http://localhost:9200
      - Elastic-Index=http://localhost:9200
      - Elastic-Username=
      - Elastic-Password=
      - E-RabbitMQ-Host=host.docker.internal
      - E-RabbitMQ-Port=5672
      - E-RabbitMQ-Username=guest
      - E-RabbitMQ-Password=guest
      - I-RabbitMQ-Host=
      - I-RabbitMQ-Port=
      - I-RabbitMQ-Username=
      - I-RabbitMQ-Password=
      - E-RedisConnectionString=
      - I-RedisConnectionString=
      - MongoConnectionString=
      - C-SqlServerConnectionString=
      - Q-SqlServerConnectionString=Server=domic.auth.sql.server,1433;Database=AuthService;User ID=sa;Password=Hasan313@@313!!;MultipleActiveResultSets=true;
      - Host=domic.auth.api
      - Port=443
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Dotris313@313%%
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Karami.WebAPI.pfx
    depends_on:
      - domic.auth.sql.server
  
  domic.auth.sql.server:
    networks:
      - domic
    image: 'mcr.microsoft.com/mssql/server'
    container_name: 'auth_sql_server'
    ports:
      - 1439:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Hasan313@@313!!

volumes:
  log:
    
networks:
  domic:
    external: true